/**
 * @file Dashboard.jsx
 * @description Team meeting dashboard view allowing users to launch meeting bots, view active/past meetings, edit topics, and access review pages.
 */

import { useState, useEffect, useRef } from 'react'
import { useNavigate, useParams, useLocation } from 'react-router-dom'
import { startMeeting, getMeetings, renameMeeting, deleteMeeting, getTopics, addMeetingTopic, removeMeetingTopic } from '../api'
import { meetingToCard } from '../utils'
import MeetingTopicTags from '../components/MeetingTopicTags'
import './Dashboard.css'

/**
 * Parses Microsoft Teams join URLs or meeting IDs to extract native ID and optional passcode.
 *
 * @param {string} raw - Raw input URL or ID string.
 * @returns {Object|null} Object containing nativeId and passcode, or null if invalid.
 */
function parseTeamsUrl(raw) {
  const trimmed = raw.trim()
  const passcodeMatch = trimmed.match(/[?&]p=([^&\s#]+)/i)
  const passcode = passcodeMatch ? decodeURIComponent(passcodeMatch[1]) : ''

  if (/^\d{10,20}$/.test(trimmed)) return { nativeId: trimmed, passcode }

  // teams.live.com/meetingOptions/meetings/{id}/view (meeting options page)
  const meetingOptionsMatch = trimmed.match(/teams\.live\.com\/meetingOptions\/meetings\/(\d{10,20})/i)
  if (meetingOptionsMatch) return { nativeId: meetingOptionsMatch[1], passcode }

  // teams.live.com/meet/{id}?p={passcode}
  const liveMatch = trimmed.match(/teams\.live\.com\/meet\/(\d{10,20})/i)
  if (liveMatch) return { nativeId: liveMatch[1], passcode }

  // *.teams.microsoft.com/meet/{id}?p={passcode}
  const msShortMatch = trimmed.match(/(?:^|\/\/)(?:[^/]+\.)?teams\.microsoft\.com\/meet\/(\d{10,20})/i)
  if (msShortMatch) return { nativeId: msShortMatch[1], passcode }

  // *.teams.microsoft.com/l/meetup-join/{thread}/...
  const msMatch = trimmed.match(/(?:^|\/\/)(?:[^/]+\.)?teams\.microsoft\.com\/l\/meetup-join\/([^\s?#/]+)/i)
  if (msMatch) return { nativeId: decodeURIComponent(msMatch[1]).split('/')[0], passcode }

  return null
}

/**
 * Fallback helper to extract trailing path segment as native meeting ID from URL string.
 *
 * @param {string} url - Meeting URL string.
 * @returns {string|null} Native ID string.
 */
function extractNativeId(url) {
  try {
    return new URL(url).pathname.split('/').filter(Boolean).pop() || null
  } catch {
    return url.trim().split('/').filter(Boolean).pop() || null
  }
}

function speakerColor(name) {
  const colors = ['#4f8ef7', '#3fb950', '#bc8cff', '#d29922', '#e3884c', '#f85149']
  let hash = 0
  for (const c of name) hash = (hash * 31 + c.charCodeAt(0)) & 0xffff
  return colors[hash % colors.length]
}

function initials(name) {
  return name.split(' ').map((n) => n[0]).join('').toUpperCase()
}


function MeetingCard({ meeting, teamId, teamTopics, onRename, onDelete, onAddTopic, onRemoveTopic }) {
  const navigate = useNavigate()
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState(meeting.title)
  const [saving, setSaving] = useState(false)
  const [confirmDelete, setConfirmDelete] = useState(false)
  const inputRef = useRef(null)

  useEffect(() => {
    if (editing) inputRef.current?.select()
  }, [editing])

  const startEdit = (e) => {
    e.stopPropagation()
    setDraft(meeting.title)
    setEditing(true)
  }

  const saveEdit = async () => {
    const trimmed = draft.trim()
    if (!trimmed || trimmed === meeting.title) { setEditing(false); return }
    setSaving(true)
    try { await onRename(meeting.id, trimmed) } catch {}
    setSaving(false)
    setEditing(false)
  }

  const isSummarizing = Boolean(meeting.isSummarizing)

  return (
    <div className={`dash-card ${isSummarizing ? 'dash-card--summarizing' : !meeting.reviewed ? 'dash-card--pending' : ''}`}>
      <div className="dash-card-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          {isSummarizing ? (
            <span className="dash-status dash-status--summarizing">
              <span className="dash-status-pulse-blue" />
              Generating AI Summary…
            </span>
          ) : meeting.reviewed ? (
            <span className="dash-status dash-status--reviewed">
              <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                <polyline points="20 6 9 17 4 12" />
              </svg>
              Finalized
            </span>
          ) : (
            <span className="dash-status dash-status--pending">
              <span className="dash-status-pulse" />
              In Progress
            </span>
          )}
          {meeting.summary && !isSummarizing && (
            <span style={{ fontSize: '10px', color: 'var(--accent)', background: 'var(--accent-dim)', padding: '1px 5px', borderRadius: '3px', fontWeight: 600 }} title="Summary generated by AI">
              AI
            </span>
          )}
          {(() => {
            const mType = meeting.meeting_type || 'general'
            const typeConfig = {
              daily_standup: {
                label: 'Standup',
                icon: (
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                    <line x1="16" y1="2" x2="16" y2="6" />
                    <line x1="8" y1="2" x2="8" y2="6" />
                    <line x1="3" y1="10" x2="21" y2="10" />
                  </svg>
                ),
                color: '#f59e0b',
                bg: 'rgba(245, 158, 11, 0.12)',
              },
              sprint_planning: {
                label: 'Sprint',
                icon: (
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
                    <rect x="8" y="2" width="8" height="4" rx="1" ry="1" />
                  </svg>
                ),
                color: '#8b5cf6',
                bg: 'rgba(139, 92, 246, 0.12)',
              },
              general: {
                label: 'General',
                icon: (
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
                    <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                    <line x1="12" y1="19" x2="12" y2="23" />
                    <line x1="8" y1="23" x2="16" y2="23" />
                  </svg>
                ),
                color: '#64748b',
                bg: 'rgba(100, 116, 139, 0.12)',
              },
            }[mType] || {
              label: mType,
              icon: (
                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
                  <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                  <line x1="12" y1="19" x2="12" y2="23" />
                  <line x1="8" y1="23" x2="16" y2="23" />
                </svg>
              ),
              color: '#64748b',
              bg: 'rgba(100, 116, 139, 0.12)',
            }
            return (
              <span
                style={{
                  fontSize: '10px',
                  fontWeight: 600,
                  color: typeConfig.color,
                  background: typeConfig.bg,
                  border: `1px solid ${typeConfig.color}44`,
                  padding: '1px 6px',
                  borderRadius: '3px',
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '4px',
                }}
                title={`Mode: ${typeConfig.label}`}
              >
                <span style={{ display: 'inline-flex', alignItems: 'center' }}>{typeConfig.icon}</span>
                <span>{typeConfig.label}</span>
              </span>
            )
          })()}
        </div>
        <span className="dash-card-date">{meeting.date}</span>
      </div>

      <div className="dash-card-title-row">
        {editing ? (
          <input
            ref={inputRef}
            className="dash-rename-input"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') saveEdit()
              if (e.key === 'Escape') setEditing(false)
            }}
            onBlur={saveEdit}
            disabled={saving}
          />
        ) : (
          <>
            <h3 className="dash-card-title">{meeting.title}</h3>
            <button className="dash-rename-btn" onClick={startEdit} title="Rename">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
              </svg>
            </button>
          </>
        )}
      </div>

      {isSummarizing ? (
        <div className="dash-card-summarizing-box">
          <div className="dash-spinner-small" />
          <span>AI multi-agent synthesis in progress...</span>
        </div>
      ) : (
        <p className="dash-card-summary">{meeting.summary}</p>
      )}

      <div className="dash-card-speakers">
        {meeting.speakers.length > 0 && (
          <>
            <span className="dash-card-speakers-label">Identified speakers:</span>
            {meeting.speakers.map((name) => (
              <span key={name} className="dash-speaker" title={name}>
                <span className="dash-speaker-avatar" style={{ background: speakerColor(name) }}>
                  {initials(name)}
                </span>
                <span className="dash-speaker-name">{name}</span>
              </span>
            ))}
          </>
        )}
      </div>

      <div className="dash-card-meta-row">
        <span className="dash-card-meta-item">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="12" cy="12" r="10" />
            <polyline points="12 6 12 12 16 14" />
          </svg>
          {meeting.duration}
        </span>
      </div>

      {teamTopics.length > 0 && (
        <div className="dash-card-topics">
          <MeetingTopicTags
            meetingTopics={meeting.topics}
            teamTopics={teamTopics}
            onAdd={(topicId, topic) => onAddTopic(meeting.id, topicId, topic)}
            onRemove={(topicId) => onRemoveTopic(meeting.id, topicId)}
            dropUp
          />
        </div>
      )}

      <div className="dash-card-stats">
        <div className="dash-stat">
          <span className="dash-stat-num">{meeting.actionItemCount}</span>
          <span className="dash-stat-label">action items</span>
        </div>
        <div className="dash-stat-divider" />
        <div className="dash-stat">
          <span className="dash-stat-num" style={{ color: meeting.parkingLotCount > 0 ? 'var(--yellow)' : 'var(--text-3)' }}>
            {meeting.parkingLotCount}
          </span>
          <span className="dash-stat-label">parking lot</span>
        </div>
      </div>

      <div className="dash-card-footer">
        {confirmDelete ? (
          <div className="dash-delete-confirm">
            <span>Delete?</span>
            <button className="dash-delete-yes" onClick={() => onDelete(meeting.id)}>Delete</button>
            <button className="dash-delete-no" onClick={() => setConfirmDelete(false)}>Cancel</button>
          </div>
        ) : (
          <button className="dash-delete-btn" onClick={() => setConfirmDelete(true)} title="Delete meeting">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="3 6 5 6 21 6" />
              <path d="M19 6l-1 14H6L5 6" />
              <path d="M10 11v6M14 11v6" />
              <path d="M9 6V4h6v2" />
            </svg>
          </button>
        )}
        <div className="dash-card-actions">
          {!meeting.reviewed && !isSummarizing && (
            <button
              className="dash-card-cta dash-card-cta--live"
              onClick={() => navigate(`/teams/${teamId}/live/${meeting.id}`)}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10" />
                <polygon points="10 8 16 12 10 16" fill="currentColor" stroke="none" />
              </svg>
              Go to live meeting
            </button>
          )}
          <button
            className={`dash-card-cta ${isSummarizing ? 'dash-card-cta--summarizing' : !meeting.reviewed ? 'dash-card-cta--pending' : ''}`}
            onClick={() => navigate(`/teams/${teamId}/review/${meeting.id}`)}
          >
            {isSummarizing ? 'View Progress' : 'View Detail'}
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <line x1="5" y1="12" x2="19" y2="12" />
              <polyline points="12 5 19 12 12 19" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  )
}

export default function Dashboard() {
  const { teamId } = useParams()
  const navigate = useNavigate()
  const location = useLocation()
  const [welcomeTeam, setWelcomeTeam] = useState(location.state?.welcome ?? null)
  const [platform, setPlatform] = useState('google_meet')
  const [url, setUrl] = useState('')
  const [passcode, setPasscode] = useState('')
  const [meetingType, setMeetingType] = useState('general')
  const [dispatchState, setDispatchState] = useState('idle')
  const [dispatchError, setDispatchError] = useState('')
  const [filter, setFilter] = useState('all')
  const [search, setSearch] = useState('')
  const [topicFilter, setTopicFilter] = useState([])
  const [meetings, setMeetings] = useState([])
  const [teamTopics, setTeamTopics] = useState([])

  useEffect(() => {
    let timer = null
    const fetchMeetings = () => {
      getMeetings(teamId)
        .then((data) => {
          const cards = (data || []).map(meetingToCard)
          setMeetings(cards)
        })
        .catch((e) => console.warn('[Dashboard] fetch failed:', e))
    }

    fetchMeetings()
    getTopics(teamId)
      .then((data) => setTeamTopics(data.topics ?? []))
      .catch(() => {})

    timer = setInterval(fetchMeetings, 4000)

    return () => {
      if (timer) clearInterval(timer)
    }
  }, [teamId])

  const handleDispatch = async () => {
    if (!url.trim() || dispatchState !== 'idle') return

    let nativeId, resolvedPasscode
    if (platform === 'teams') {
      const parsed = parseTeamsUrl(url.trim())
      if (!parsed) {
        setDispatchError('Could not parse Teams URL. Paste the full meeting link.')
        return
      }
      nativeId = parsed.nativeId
      resolvedPasscode = passcode.trim() || parsed.passcode
    } else {
      nativeId = extractNativeId(url.trim())
      resolvedPasscode = ''
    }

    if (!nativeId) {
      setDispatchError('Invalid meeting URL')
      return
    }
    setDispatchState('loading')
    setDispatchError('')
    try {
      const { meeting_id } = await startMeeting(platform, nativeId, teamId, resolvedPasscode, meetingType)
      setDispatchState('done')
      setTimeout(() => navigate(`/teams/${teamId}/live/${meeting_id}?native=${encodeURIComponent(nativeId)}`), 800)
    } catch (err) {
      setDispatchState('idle')
      setDispatchError(err.message)
    }
  }

  const handleRename = async (id, newTitle) => {
    await renameMeeting(id, newTitle)
    setMeetings((prev) => prev.map((m) => m.id === id ? { ...m, title: newTitle } : m))
  }

  const handleDelete = async (id) => {
    await deleteMeeting(id)
    setMeetings((prev) => prev.filter((m) => m.id !== id))
  }

  const handleAddTopic = async (meetingId, topicId, topic) => {
    try {
      await addMeetingTopic(meetingId, topicId)
      setMeetings((prev) => prev.map((m) =>
        m.id === meetingId ? { ...m, topics: [...m.topics, topic] } : m
      ))
    } catch (err) {
      console.warn('[Dashboard] add topic failed:', err)
    }
  }

  const handleRemoveTopic = async (meetingId, topicId) => {
    try {
      await removeMeetingTopic(meetingId, topicId)
      setMeetings((prev) => prev.map((m) =>
        m.id === meetingId ? { ...m, topics: m.topics.filter((t) => t.id !== topicId) } : m
      ))
    } catch (err) {
      console.warn('[Dashboard] remove topic failed:', err)
    }
  }

  const toggleTopicFilter = (id) => {
    setTopicFilter((prev) => prev.includes(id) ? prev.filter((t) => t !== id) : [...prev, id])
  }

  const filtered = meetings
    .filter((m) => {
      if (filter === 'pending') return !m.reviewed
      if (filter === 'reviewed') return m.reviewed
      return true
    })
    .filter((m) => !search.trim() || m.title.toLowerCase().includes(search.toLowerCase()))
    .filter((m) => topicFilter.length === 0 || topicFilter.every((id) => m.topics.some((t) => t.id === id)))

  return (
    <div className="dash-page">
      <div className="page-header">
        <div className="page-header-left">
          <h1 className="page-title">Dashboard</h1>
          <p className="page-sub">Overview of your meetings and action items</p>
        </div>
      </div>

      {welcomeTeam && (
        <div className="dash-welcome-banner">
          <span>
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="20 6 9 17 4 12" />
            </svg>
            Welcome to <strong>{welcomeTeam}</strong>! You have joined the team.
          </span>
          <button className="dash-welcome-close" onClick={() => setWelcomeTeam(null)}>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      )}

      <div className="dash-join-box">
        <div className="dash-join-box-left">
          <div className="dash-join-box-title">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polygon points="23 7 16 12 23 17 23 7" />
              <rect x="1" y="5" width="15" height="14" rx="2" ry="2" />
            </svg>
            Start a New Meeting
          </div>
          <p className="dash-join-box-sub">Dispatch AI agents to an active meeting session</p>
        </div>
        <div className="dash-mode-selector" style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px', flexWrap: 'wrap' }}>
          <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-2)', marginRight: '4px' }}>Meeting Mode:</span>
          {[
            {
              key: 'general',
              label: 'General Meeting',
              icon: (
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
                  <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                  <line x1="12" y1="19" x2="12" y2="23" />
                  <line x1="8" y1="23" x2="16" y2="23" />
                </svg>
              ),
              desc: 'Standard elapsed pacing',
            },
            {
              key: 'daily_standup',
              label: 'Daily Stand-up',
              icon: (
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
                  <line x1="16" y1="2" x2="16" y2="6" />
                  <line x1="8" y1="2" x2="8" y2="6" />
                  <line x1="3" y1="10" x2="21" y2="10" />
                </svg>
              ),
              desc: '15m timebox & blocker priority',
            },
            {
              key: 'sprint_planning',
              label: 'Sprint Sync',
              icon: (
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
                  <rect x="8" y="2" width="8" height="4" rx="1" ry="1" />
                </svg>
              ),
              desc: 'Backlog & scope alignment',
            },
          ].map((mode) => {
            const isSelected = meetingType === mode.key
            return (
              <button
                key={mode.key}
                type="button"
                onClick={() => setMeetingType(mode.key)}
                disabled={dispatchState !== 'idle'}
                title={mode.desc}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '6px',
                  padding: '5px 12px',
                  borderRadius: '20px',
                  fontSize: '12px',
                  fontWeight: isSelected ? 600 : 400,
                  cursor: dispatchState === 'idle' ? 'pointer' : 'default',
                  transition: 'all 0.15s ease',
                  border: isSelected ? '1px solid var(--accent)' : '1px solid var(--border)',
                  background: isSelected ? 'rgba(79, 142, 247, 0.12)' : 'var(--bg-2)',
                  color: isSelected ? 'var(--accent)' : 'var(--text-2)',
                }}
              >
                <span style={{ display: 'inline-flex', alignItems: 'center' }}>{mode.icon}</span>
                <span>{mode.label}</span>
              </button>
            )
          })}
        </div>
        <div className="dash-join-input-row">
          <select
            className="dash-platform-select"
            value={platform}
            onChange={(e) => { setPlatform(e.target.value); setPasscode(''); setDispatchError('') }}
            disabled={dispatchState !== 'idle'}
            aria-label="Meeting platform"
          >
            <option value="google_meet">Google Meet</option>
            <option value="teams">Microsoft Teams</option>
          </select>
          <div className={`dash-join-input-group ${url ? 'dash-join-input-group--filled' : ''}`}>
            <input
              className="dash-join-input"
              type="url"
              placeholder={platform === 'teams' ? 'Paste Teams meeting link' : 'Paste meeting URL'}
              value={url}
              onChange={(e) => { setUrl(e.target.value); setDispatchError('') }}
              onKeyDown={(e) => e.key === 'Enter' && handleDispatch()}
              disabled={dispatchState !== 'idle'}
            />
          </div>
          {platform === 'teams' && (
            <div className={`dash-join-input-group ${passcode ? 'dash-join-input-group--filled' : ''}`}>
              <input
                className="dash-join-input"
                type="text"
                placeholder="Passcode (if not in link)"
                value={passcode}
                onChange={(e) => { setPasscode(e.target.value); setDispatchError('') }}
                onKeyDown={(e) => e.key === 'Enter' && handleDispatch()}
                disabled={dispatchState !== 'idle'}
                style={{ width: '160px' }}
              />
            </div>
          )}
          <button
            className={`dash-join-btn ${dispatchState === 'loading' ? 'dash-join-btn--loading' : ''} ${dispatchState === 'done' ? 'dash-join-btn--done' : ''}`}
            onClick={handleDispatch}
            disabled={dispatchState !== 'idle' || !url.trim()}
          >
            {dispatchState === 'idle' && (
              <>
                Dispatch Bot
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="5" y1="12" x2="19" y2="12" />
                  <polyline points="12 5 19 12 12 19" />
                </svg>
              </>
            )}
            {dispatchState === 'loading' && (
              <>
                <span className="dash-join-spinner" />
                Dispatching…
              </>
            )}
            {dispatchState === 'done' && (
              <>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
                Joined
              </>
            )}
          </button>
        </div>
      </div>

      {dispatchError && (
        <p style={{ color: 'var(--red)', fontSize: '13px', marginTop: '-8px', marginBottom: '8px', paddingLeft: '4px' }}>
          {dispatchError}
        </p>
      )}

      <div className="dash-meetings-section">
        <div className="dash-meetings-header">
          <div className="dash-meetings-header-left">
            <span className="dash-section-label">Past Meetings</span>
            <div className="dash-search-wrap">
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="11" cy="11" r="8" />
                <line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
              <input
                className="dash-search-input"
                placeholder="Search meetings..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
              {search && (
                <button className="dash-search-clear" onClick={() => setSearch('')} title="Clear">
                  <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </button>
              )}
            </div>
          </div>
          <div className="dash-filter-tabs">
            {[
              { key: 'all', label: `All (${meetings.length})` },
              { key: 'pending', label: `In Progress (${meetings.filter((m) => !m.reviewed).length})` },
              { key: 'reviewed', label: 'Finalized' },
            ].map((f) => (
              <button
                key={f.key}
                className={`dash-filter-tab ${filter === f.key ? 'dash-filter-tab--active' : ''}`}
                onClick={() => setFilter(f.key)}
              >
                {f.label}
              </button>
            ))}
          </div>
        </div>

        {teamTopics.length > 0 && (
          <div className="dash-topic-filter-row">
            <span className="dash-topic-filter-label">Topics:</span>
            {teamTopics.map((t) => {
              const active = topicFilter.includes(t.id)
              return (
                <button
                  key={t.id}
                  className={`dash-topic-filter-chip ${active ? 'dash-topic-filter-chip--active' : ''}`}
                  style={active ? { background: t.color + '22', color: t.color, borderColor: t.color + '88' } : {}}
                  onClick={() => toggleTopicFilter(t.id)}
                >
                  <span className="dash-topic-filter-dot" style={{ background: t.color }} />
                  {t.name}
                </button>
              )
            })}
            {topicFilter.length > 0 && (
              <button className="dash-topic-filter-clear" onClick={() => setTopicFilter([])}>
                Clear
              </button>
            )}
          </div>
        )}

        {filtered.length > 0 ? (
          <div className="dash-meetings-grid">
            {filtered.map((m) => (
              <MeetingCard
                key={m.id}
                meeting={m}
                teamId={teamId}
                teamTopics={teamTopics}
                onRename={handleRename}
                onDelete={handleDelete}
                onAddTopic={handleAddTopic}
                onRemoveTopic={handleRemoveTopic}
              />
            ))}
          </div>
        ) : (
          <div className="dash-empty">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <polyline points="20 6 9 17 4 12" />
            </svg>
            <p>{search ? 'No meetings match your search' : 'No meetings match this filter'}</p>
          </div>
        )}
      </div>
    </div>
  )
}
